spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path= /api/authenticate/**
        - id: PROFILE-SERVICE
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path= /api/profile/**
        - id: EDUCATION-SERVICE
          uri: lb://EDUCATION-SERVICE
          predicates:
            - Path= /api/education/**
        - id: EXPERIENCE-SERVICE
          uri: lb://EXPERIENCE-SERVICE
          predicates:
            - Path= /api/experience/**
server:
  port: 9191
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: mySecretKey
  expireMs: 1200
  refrEshexpireMs: 1200
