spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path= /user/**
        - id: PROFILE-SERVICE
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path= /profile/**
        - id: EDUCATION-SERVICE
          uri: lb://EDUCATION-SERVICE
          predicates:
            - Path= /education/**
        - id: EXPERIENCE-SERVICE
          uri: lb://EXPERIENCE-SERVICE
          predicates:
            - Path= /experience/**
        - id : AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path= /authenticate/**
server:
  port: 9191
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: mySecretKey
  expireMs: 120000
  refrEshexpireMs: 120000
