spring:
  datasource:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/profile
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: PROFILE-SERVICE
server:
  port: 0
  error:
    include-message: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
api:
  user: http://AUTH-SERVICE/api/authenticate
  user1: http://AUTH-SERVICE/api/authenticate/user
